// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0SLTiSqVEEkkeHBJJwS4nx8VjPijmnPY',
    appId: '1:1092729837398:android:d2b26cd4f2bde35428e8f7',
    messagingSenderId: '1092729837398',
    projectId: 'nodemcutest-ae41d',
    databaseURL: 'https://nodemcutest-ae41d-default-rtdb.firebaseio.com',
    storageBucket: 'nodemcutest-ae41d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt2QDObObyh_zOJbDQc8w6_XyraZQJzQI',
    appId: '1:1092729837398:ios:2c928c5c1e6337d328e8f7',
    messagingSenderId: '1092729837398',
    projectId: 'nodemcutest-ae41d',
    databaseURL: 'https://nodemcutest-ae41d-default-rtdb.firebaseio.com',
    storageBucket: 'nodemcutest-ae41d.appspot.com',
    iosBundleId: 'com.mahendranmurugan.waterLevelManagementSystem',
  );
}
